const subjectsData = [
  {
    category: "School Tuition",
    tuition: [
      "LKG",
      "UKG",
      "Class I-V Tuition",
      "Class 6 Tuition",
      "Class 7 Tuition",
      "Class 8 Tuition",
      "Class 9 Tuition",
      "Class IX Tuition in Class 9 Tuition",
      "Class 10 Tuition",
      "Class X Tuition in Class 10 Tuition",
      "Class 11 Tuition",
      "Class XI Tuition in Class 11 Tuition",
      "Class 12 Tuition",
      "Class XII Tuition in Class 12 Tuition",
         "Diploma in Engineering",
        "Diploma in Hotel Management",
    ]
  },
  {
    category: "Degree Programs",
    tuition: [
      "B.Sc",
      "B.Com",
      "BA",
      "BBA",
      "BCA",
      "B.Tech",
      "B.Arch (Architecture)",
        "BCA (Computer Applications)",
        "BBA (Business Administration)",
        "MBBS (Medicine)",
        "B.Pharm (Pharmacy)",
        "L.L.B (Law)",
        "B.Voc (Vocational Degree)",
      "B.Ed (Education)",
      "B.Sc (Hons)",
      "B.Com (Hons)",
      "B.A (Hons)",
      "BBA (Hons)",
      "BCA (Hons)",
      "B.Tech (Hons)",    
      "M.Sc",
      "M.Com",
   
      "MBA",
      "MCA",
      "M.Tech",
       "M.A. (Master of Arts)",
        "M.Sc. (Master of Science)",
        "M.Com (Master of Commerce)",
        "MBA (Master of Business Administration)",
        "M.Tech / M.E. (Engineering)",
        "M.Arch (Architecture)",
        "MCA (Computer Applications)",
        "M.L.L.M (Master of Laws)",
        "M.Pharm (Pharmacy)",
        "M.Ed (Education)",
        "M.Des (Design)",
        "M.S.W (Social Work)",
         "Ph.D. (Doctor of Philosophy)",
        "D.M. (Doctor of Medicine, Super‑speciality)",
        "M.Ch. (Master of Chirurgiae, Surgical super‑speciality)",
        "Pharm.D (Doctor of Pharmacy specialization)"
    ]
  },
  {
    category: "IT Courses",
    tuition: [
      "Web Development",
      "App Development",
      "Data Science",
      "Machine Learning",
      "Cloud Computing",
      "Cyber Security",
      "UI/UX Design",
      "Full Stack Development",
      "DevOps",
      "Artificial Intelligence",
      "Data Engineering",
      "Digital Marketing"
    ]
  },
  {
    category: "Programming Languages",
    tuition: [
      "Python",
      "JavaScript",
      "Java",
      "C",
      "C++",
      "C#",
      "PHP",
      "TypeScript",
      "Ruby",
      "Go",
      "Swift",
      "Kotlin",
      "R",
      "Perl",
      "Scala",
      "Rust",
      "SQL",
      "HTML",
      "CSS",
      "React",
      "Angular",      
      "Vue.js",
      "Other"
    ]
  }
];

export default subjectsData;